# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 541))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.start_transcription_button = QtWidgets.QPushButton(self.layoutWidget)
        self.start_transcription_button.setObjectName("start_transcription_button")
        self.gridLayout.addWidget(self.start_transcription_button, 0, 1, 1, 1)
        self.select_files_button = QtWidgets.QPushButton(self.layoutWidget)
        self.select_files_button.setObjectName("select_files_button")
        self.gridLayout.addWidget(self.select_files_button, 0, 0, 1, 1)
        self.files_list_widget = QtWidgets.QListWidget(self.layoutWidget)
        self.files_list_widget.setObjectName("files_list_widget")
        self.gridLayout.addWidget(self.files_list_widget, 1, 0, 1, 2)
        self.text_viewer = QtWidgets.QLabel(self.layoutWidget)
        self.text_viewer.setWordWrap(True)
        self.text_viewer.setObjectName("text_viewer")
        self.gridLayout.addWidget(self.text_viewer, 1, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transcriber"))
        self.start_transcription_button.setText(_translate("MainWindow", "Start transcription"))
        self.select_files_button.setText(_translate("MainWindow", "Select files"))
        self.text_viewer.setText(_translate("MainWindow", "Waiting for transcriptions"))
